image: node:12

.base:
  before_script:
    - yarn install --frozen-lockfile

stages:
  - lint
  - deploy

lint:
  extends: .base
  stage: lint
  script:
    - yarn lint

pages:
  extends: .base
  stage: deploy
  script:
    - yarn storybook:build
  artifacts:
    paths:
      - public
    expire_in: 7 day
  only:
    - tags
  needs:
    - lint
