image: node:12

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint --no-fix

pages:
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn storybook:build
  artifacts:
    paths:
      - public
    expire_in: 7 day
  only:
    - tags
