// TODO IMPORT THIS FILE IN PROJECT TO KEEP RIGHT DATA / ACTIONS
export const TASK_STATUS_VALUES = {
  DONE: 'DONE',
  IN_PROGRESS: 'ONGOING',
  TODO: 'TODO',
  ARCHIVED: 'ARCHIVED',
}

export const FAKER_TASK_STATUS_NAMES = {
  DONE: 'DONE',
  IN_PROGRESS: 'ONGOING',
  TODO: 'TODO',
  ARCHIVED: 'ARCHIVED',
}

const statusTypes = (action) => ({
  pending: `${action}_PENDING`,
  started: `${action}_STARTED`,
  paused: `${action}_PAUSED`,
  done: `${action}_DONE`,
})

export const POMODORO_STATUS = {
  SESSION: statusTypes(`SESSION`),
  POMODORO: statusTypes(`POMODORO`),
  SMALL_BREAK: statusTypes(`SMALL_BREAK`),
  BIG_BREAK: statusTypes(`BIG_BREAK`),
}

export const SPACEBAR_KEY_CODE = [0, 32]
export const ENTER_KEY_CODE = 13
export const DOWN_ARROW_KEY_CODE = 40
export const UP_ARROW_KEY_CODE = 38
export const ESCAPE_KEY_CODE = 27

/*
 Settings panel
 */
export const SETTINGS_PANEL_STEPS_VALUES = {
  GENERAL: 'GENERAL',
  ACCOUNT: 'ACCOUNT',
  POMODORO_CONFIG: 'POMODORO_CONFIGURATION',
  SUBSCRIPTION: 'SUBSCRIPTION',
  ABOUT: 'ABOUT',
  HELP: 'HELP',
}

export const SETTINGS_PANEL_STEPS_NAMES = {
  GENERAL: 'General',
  ACCOUNT: 'Account',
  POMODORO_CONFIG: 'Pomodoro configuration',
  SUBSCRIPTION: 'Subscription',
  ABOUT: 'About',
  HELP: 'Help',
}

export const SETTINGS_PANEL_STEPS = [
  {
    step: SETTINGS_PANEL_STEPS_VALUES.GENERAL,
    name: SETTINGS_PANEL_STEPS_NAMES.GENERAL,
  },
  {
    step: SETTINGS_PANEL_STEPS_VALUES.ACCOUNT,
    name: SETTINGS_PANEL_STEPS_NAMES.ACCOUNT,
  },
  {
    step: SETTINGS_PANEL_STEPS_VALUES.POMODORO_CONFIG,
    name: SETTINGS_PANEL_STEPS_NAMES.POMODORO_CONFIG,
  },
  {
    step: SETTINGS_PANEL_STEPS_VALUES.SUBSCRIPTION,
    name: SETTINGS_PANEL_STEPS_NAMES.SUBSCRIPTION,
  },
  //   step: SETTINGS_PANEL_STEPS_VALUES.ABOUT,
  //   name: SETTINGS_PANEL_STEPS_NAMES.ABOUT,
  // },
  // {
  //   step: SETTINGS_PANEL_STEPS_VALUES.HELP,
  //   name: SETTINGS_PANEL_STEPS_NAMES.HELP,
  // },
]

export const SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES = {
  OVERVIEW: 'OVERVIEW',
  ESTIMATE_OF_INVOICE: 'ESTIMATE_OF_INVOICE',
  INVOICE_INFORMATIONS: 'INVOICE_INFORMATIONS',
  BILLING_HISTORY: 'BILLING_HISTORY',
  CURRENT_SUBSCRIPTION: ' CURRENT_SUBSCRIPTION',
}

export const SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES = {
  OVERVIEW: 'Overview',
  ESTIMATE_OF_INVOICE: 'Estimate of the invoice',
  INVOICE_INFORMATIONS: 'Invoice informations',
  BILLING_HISTORY: 'Billing history',
  CURRENT_SUBSCRIPTION: 'Current subscription',
}

export const SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS = [
  {
    step: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES.OVERVIEW,
    name: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES.OVERVIEW,
  },
  {
    step: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES.ESTIMATE_OF_INVOICE,
    name: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES.ESTIMATE_OF_INVOICE,
  },
  {
    step: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES.INVOICE_INFORMATIONS,
    name: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES.INVOICE_INFORMATIONS,
  },
  {
    step: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES.BILLING_HISTORY,
    name: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES.BILLING_HISTORY,
  },
  {
    step: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES.CURRENT_SUBSCRIPTION,
    name: SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_NAMES.CURRENT_SUBSCRIPTION,
  },
]
