// TODO IMPORT THIS FILE IN PROJECT TO KEEP RIGHT DATA / ACTIONS
export const TASK_STATUS = {
  COMPLETED: 'COMPLETED',
  IN_PROGRESS: 'IN_PROGRESS',
  TODO: 'TODO',
  ARCHIVED: 'ACRHIVED',
}

export const SPACEBAR_KEY_CODE = [0, 32]
export const ENTER_KEY_CODE = 13
export const DOWN_ARROW_KEY_CODE = 40
export const UP_ARROW_KEY_CODE = 38
export const ESCAPE_KEY_CODE = 27
