export const SPACEBAR_KEY_CODE = [0, 32]
export const ENTER_KEY_CODE = 13
export const DOWN_ARROW_KEY_CODE = 40
export const UP_ARROW_KEY_CODE = 38
export const ESCAPE_KEY_CODE = 27

export const SIDEBAR_TOGGLE_ANIMATION_TIMEOUT = 500
export const aMinuteInMilliseconds = 60000
export const aSecondInMilliseconds = 1000

export const TIME_FORMAT_24h = 'HH:mm'
export const TIME_FORMAT_12H = 'hh:mm A'

/*
  Status
*/
export const TASK_STATUS_VALUES = {
  DONE: 'DONE',
  IN_PROGRESS: 'IN_PROGRESS',
  TODO: 'TODO',
  ARCHIVED: 'ARCHIVED',
}

export const STEPS_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  PAUSED: 'PAUSED',
  DONE: 'DONE',
  SKIPPED: 'SKIPPED',
}

export const SESSION_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  PAUSED: 'PAUSED',
  DONE: 'DONE',
  ABORTED: 'ABORTED',
}

/*
  Types
*/
export const ACTION_TYPES = {
  START: 'START',
  RESUME: 'RESUME',
  PAUSE: 'PAUSE',
  FINISH: 'FINISH',
  SKIP: 'SKIP',
}

export const STEPS_TYPES = {
  POMODORO: `POMODORO`,
  SMALL_BREAK: `SMALL_BREAK`,
  BIG_BREAK: `BIG_BREAK`,
}

/*
  Settings panel tabs values
*/
export const SETTINGS_PANEL_STEPS_VALUES = {
  GENERAL: 'GENERAL',
  ACCOUNT: 'ACCOUNT',
  POMODORO_CONFIG: 'POMODORO_CONFIGURATION',
  SUBSCRIPTION: 'SUBSCRIPTION',
  ABOUT: 'ABOUT',
  HELP: 'HELP',
}

export const SETTINGS_PANEL_SUBSCRIPTION_CHILDREN_STEPS_VALUES = {
  OVERVIEW: 'OVERVIEW',
  ESTIMATE_OF_INVOICE: 'ESTIMATE_OF_INVOICE',
  INVOICE_INFORMATIONS: 'INVOICE_INFORMATIONS',
  BILLING_HISTORY: 'BILLING_HISTORY',
  CURRENT_SUBSCRIPTION: ' CURRENT_SUBSCRIPTION',
}

// TODO MOVE ON MOCK FOLDER
export const FAKER_TASK_STATUS_NAMES = {
  DONE: 'DONE',
  IN_PROGRESS: 'IN PROGRESS',
  TODO: 'TODO',
  ARCHIVED: 'ARCHIVED',
}
